### ISSUE TITLE
media / cover-art url wrong

### ISSUE THREAD

**Issue by Comrade3** [thetarkus/docker-funkwhale#25]
This was posted on the FunkWhale GitLab here [https://dev.funkwhale.audio/funkwhale/funkwhale/issues/790](url). I added a comment there. But I think this is probably the more relevant place to post this issue.

OP:
I am using the docker all-in-one image. (havent tried anything else), behind an nginx proxy. Everything works perfect, however all media is refered to using 127.0.0.1, so all coverart on the fronted is givint 404. If i take the url and change 127.0.0.1 to the real funkwhale domain, the cover-art will show up. You can see the code in the attachement.
In ultrasonic (android app) the cover art works, so it seems to be an issue in funkwhale frontend.
![image](https://user-images.githubusercontent.com/45407923/61325909-56f3b780-a7db-11e9-9cd8-8448218a5a78.png)

My comment:
I am also using the docker all-in-one image and having this same problem. I'm using nginx proxy also, but the album art is still messed up when I use the local ip and avoid the proxy. Changing the https://127.0.0.1:8000 in the browser dev tools to ether my domain name which uses the nginx proxy or my local ip:5000 fixes it. The album art is working perfect in the Subsonic android app I'm using though. Audinaut.

**Comment by Comrade3** [comment]
If I change the NESTED_PROXY=1 to NESTED_PROXY=0 it works on my local network. And if I connect through the nginx proxy(but still on local network) it still work because it changes the the https://127.0.0.1:8000 to my servers local ip.

**Comment by n1zzo** [comment]
The issue was caused by a missing line in the `funkwhale_proxy_nested.conf` file,
the cover URL were rendered correctly using the non-nested option, so I've added the
```
proxy_set_header X-Real-IP $remote_addr;
```
option in the nested config file.

Fixed in PR 10e83c4 .

**Comment by Comrade3** [comment]
Thank you, n1zzo. :)

**Comment by Log1x** [comment]
Can we get this pushed to Docker Hub? I feel like there may be some underlying issues even past this with my experience with CloudFlare– but I'd like to test this.

**Comment by Log1x** [comment]
Although I will point out this PR effectively reversed https://github.com/thetarkus/docker-funkwhale/issues/19 – but being that #19 didn't solve the overall issue...

**Comment by tnyeanderson** [comment]
> Also is there a difference in running funkwhale/all-in-one:0.19.1 or thetarkus/funkwhale? Which one should I be using?

Last update for `thetarkus/funkwhale` was 5 months ago. `all-in-one` seems to be more active, so use that.

Many thanks @n1zzo! Is there anything we need to do before this gets pushed?

**Comment by Log1x** [comment]
Not to shamefully plug, but in case anyone wants an image setup properly for both reverse proxy/non-reverse proxy as well as the latest version (7.0), I've created an [image](https://github.com/Log1x/docker-madsonic). You can also add my [repository](https://github.com/Log1x/docker-templates) if you use unRAID.

**Comment by valahna** [comment]
I had the same issue with the all-in-one docker image (latest pull [funkwhale / all-in-one : latest](https://hub.docker.com/layers/funkwhale/all-in-one/latest/images/sha256-3d4f3a13b012cbc44e378c2b9cc2fd0f27173a8cc79a43e139863629c75e94fc)) and neither the .env flag for ```NESTED_PROXY=1``` nor ```NESTED_PROXY=0``` resolved the issue. Adding or removing ```proxy_set_header X-Real-IP $remote_addr;``` in the ```funkwhale_proxy.conf``` or ```funkwhale_proxy_nested.conf``` file had no appreciable effect. I could not get the album art to display even when bypassing the immediate proxy.

After much digging, trial, and error, I changed: 
```proxy_set_header Host $http_x_forwarded_host;```
to 
```proxy_set_header Host $host;```
in the appropriate *proxy.conf file and suddenly album art everywhere O.O

I have this setup:
 client --> reverse_proxy & docker host --> funkwhale all-in-one container

My issue could be unique in that I am running this container on a synology NAS.
I hope it helps anyone else with this issue :)
